version: '2'
services:
  backend-app:
    image: backend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://backend-mysql:3306/backend?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://backend-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://backend-elasticsearch:9200
  backend-mysql:
    extends:
      file: mysql.yml
      service: backend-mysql
  backend-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: backend-elasticsearch
